# Generated by Django 2.1.1 on 2019-03-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_auto_20190314_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.ImageField(upload_to='uploads/eshop'),
        ),
    ]
